version: '3.3'
services:
  wordpress:
    build: .
    restart: always
    ports:
      - 80
    volumes:
      - /web:/var/www/web
    networks:
      - frontend
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    networks:
      - frontend
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: mysql

networks:
 frontend:
