version: '3.3'
services:
  october:
    build: .
    restart: always
    ports:
      - 80
    volumes:
      - web:/var/www/web
    networks:
      - webku
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    networks:
      - webku
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: mysql

networks:
 webku:
  name: webku
